---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lint
        uses: reviewdog/action-golangci-lint@v2
  test:
    strategy:
      matrix:
        go_version:
          - 1.14.x
          - 1.15.x
          - 1.16.x
          - 1.17.x
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
      - name: test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest' && matrix.go_version == '1.17.x'
